const MOCK_BUILD = {
  items: [3116, 3020, 4645, 3089, 3135, 3115, 3364],
  spells: [4, 14],
  runes: { keystone: 8229, primary: 8200, sub: 8100, perks: [8229, 8226, 8233, 8237, 8135, 8106] },
};

export const MOCK_PROFILE = {
  riotId: 'five fingers#EUW',
  profileIconId: 29,
  summonerLevel: 312,
  rank: 'MASTER',
  ladderRank: 666,
  lp: 335,
  wins: 299,
  losses: 273,
  stats: {
    kda: '3.3',
    kdaDelta: '-2.7',
    kdaDeltaDir: 'down',
    dpmScore: '60.2',
    dpmDelta: '+5.1',
    dpmDeltaDir: 'up',
    kp: '0.5',
    kpDelta: '-0.0',
    kpDeltaDir: 'flat',
    csm: '6.0',
    csmDelta: '+0.0',
    csmDeltaDir: 'flat',
    visionScore: '0.7',
    visionDelta: '-0.2',
    visionDeltaDir: 'down',
    gpm: '375.1',
    gpmDelta: '+6.6',
    gpmDeltaDir: 'up',
    goldDiff15: '-114.3',
    goldDiff15Delta: '+269.9',
    goldDiff15DeltaDir: 'up',
    kaDiff15: '0.5',
    kaDiff15Delta: '-0.5',
    kaDiff15DeltaDir: 'down',
    csPerMin: '6.0',
  },
  // sparkline data for each stat
  sparklines: {
    kda:        [2.1, 2.6, 2.4, 3.0, 2.9, 3.3, 3.1],
    dpmScore:   [52, 55, 58, 57, 60, 60.2, 59],
    kp:         [0.48, 0.52, 0.50, 0.53, 0.51, 0.50, 0.50],
    csm:        [5.4, 5.6, 5.8, 5.9, 6.1, 6.0, 6.0],
    vision:     [0.9, 0.8, 0.9, 0.7, 0.8, 0.7, 0.7],
    gpm:        [340, 350, 360, 365, 372, 375, 374],
    goldDiff15: [-200, -150, -100, 50, -114, -114, -110],
    kaDiff15:   [0.3, 0.5, 0.4, 0.6, 0.5, 0.5, 0.5],
  },
  lastGame: {
    matchId: 'm1',
    win: false,
    champion: 'Neeko',
    kills: 12,
    deaths: 4,
    assists: 16,
    kda: '8.5',
    cs: 210,
    durationMin: 34,
    durationSec: 33,
    queueType: 'Solo/Duo',
    region: 'EUW',
    earlyScore: 75,
    midScore: 86,
    lateScore: 66,
    deaths4: 4,
    killsAssists: 28,
    csm: 150,
    goldDiff15: 312,
    allyTeam: ['Neeko', 'Thresh', 'Jinx', 'Orianna', 'Malphite'],
    enemyTeam: ['Lulu', 'Caitlyn', 'Leona', 'Viktor', 'Renekton'],
    ...MOCK_BUILD,
  },
  recentGames: [
    { matchId: 'm1', win: true,  champion: 'Neeko', kills: 7,  deaths: 8,  assists: 15, cs: 210, durationMin: 35, durationSec: 12, kda: '2.8', ago: '22h ago',  lp: 73, queueType: 'Solo/Duo', queueLabel: 'Solo/Duo', region: 'EUW', allyTeam: ['Neeko', 'Thresh', 'Jinx', 'Orianna', 'Malphite'], enemyTeam: ['Lulu', 'Caitlyn', 'Leona', 'Viktor', 'Renekton'], earlyScore: 62, midScore: 70, lateScore: 55, deaths4: 8, killsAssists: 22, csm: 210, goldDiff15: 312, ...MOCK_BUILD },
    { matchId: 'm2', win: true,  champion: 'Ivern', kills: 6,  deaths: 5,  assists: 10, cs: 150, durationMin: 32, durationSec: 4, kda: '3.2', ago: '23h ago',  lp: 55, queueType: 'Solo/Duo', queueLabel: 'Solo/Duo', region: 'EUW', allyTeam: ['Ivern', 'Ahri', 'Jinx', 'Sett', 'Nautilus'], enemyTeam: ['LeeSin', 'Syndra', 'KaiSa', 'Renekton', 'Thresh'], earlyScore: 58, midScore: 64, lateScore: 72, deaths4: 5, killsAssists: 16, csm: 150, goldDiff15: -80, ...MOCK_BUILD },
    { matchId: 'm3', win: false, champion: 'Hwei',  kills: 1,  deaths: 3,  assists: 2,  cs: 190, durationMin: 21, durationSec: 40, kda: '1.0', ago: '23h ago',  lp: 20, queueType: 'Flex', queueLabel: 'Flex', region: 'EUW', allyTeam: ['Hwei', 'Vi', 'Jinx', 'Sion', 'Lulu'], enemyTeam: ['Yasuo', 'Graves', 'Caitlyn', 'Camille', 'Bard'], earlyScore: 40, midScore: 38, lateScore: 44, deaths4: 3, killsAssists: 3, csm: 190, goldDiff15: -640, ...MOCK_BUILD },
    { matchId: 'm4', win: true,  champion: 'Ivern', kills: 6,  deaths: 3,  assists: 13, cs: 160, durationMin: 31, durationSec: 18, kda: '6.3', ago: '24h ago',  lp: 92, queueType: 'Solo/Duo', queueLabel: 'Solo/Duo', region: 'EUW', allyTeam: ['Ivern', 'Azir', 'Jinx', 'Ornn', 'Rakan'], enemyTeam: ['Nidalee', 'Syndra', 'Aphelios', 'Jax', 'Nautilus'], earlyScore: 71, midScore: 80, lateScore: 74, deaths4: 3, killsAssists: 19, csm: 160, goldDiff15: 210, ...MOCK_BUILD },
    { matchId: 'm5', win: false, champion: 'Neeko', kills: 1,  deaths: 7,  assists: 17, cs: 120, durationMin: 34, durationSec: 2, kda: '2.6', ago: '4d ago',   lp: 38, queueType: 'Solo/Duo', queueLabel: 'Solo/Duo', region: 'EUW', allyTeam: ['Neeko', 'Sejuani', 'Orianna', 'KaiSa', 'Leona'], enemyTeam: ['Elise', 'Ahri', 'Jinx', 'Renekton', 'Thresh'], earlyScore: 48, midScore: 52, lateScore: 41, deaths4: 7, killsAssists: 18, csm: 120, goldDiff15: -190, ...MOCK_BUILD },
    { matchId: 'm6', win: true,  champion: 'Ivern', kills: 8,  deaths: 2,  assists: 11, cs: 175, durationMin: 38, durationSec: 9, kda: '9.5', ago: '4d ago',   lp: 59, queueType: 'Solo/Duo', queueLabel: 'Solo/Duo', region: 'EUW', allyTeam: ['Ivern', 'LeBlanc', 'Jinx', 'Malphite', 'Bard'], enemyTeam: ['LeeSin', 'Viktor', 'Caitlyn', 'Fiora', 'Pyke'], earlyScore: 77, midScore: 82, lateScore: 88, deaths4: 2, killsAssists: 19, csm: 175, goldDiff15: 480, ...MOCK_BUILD },
    { matchId: 'm7', win: false, champion: 'Ahri',  kills: 4,  deaths: 6,  assists: 8,  cs: 188, durationMin: 28, durationSec: 11, kda: '2.0', ago: '5d ago',  lp: 41, queueType: 'Solo/Duo', queueLabel: 'Solo/Duo', region: 'EUW', allyTeam: ['Ahri', 'Ivern', 'Jinx', 'Ornn', 'Nautilus'], enemyTeam: ['Syndra', 'LeeSin', 'Caitlyn', 'Camille', 'Thresh'], earlyScore: 51, midScore: 48, lateScore: 44, deaths4: 6, killsAssists: 12, csm: 188, goldDiff15: -90, ...MOCK_BUILD },
    { matchId: 'm8', win: true,  champion: 'Neeko', kills: 9,  deaths: 3,  assists: 12, cs: 201, durationMin: 29, durationSec: 44, kda: '7.0', ago: '5d ago',  lp: 81, queueType: 'ARAM', queueLabel: 'ARAM', region: 'EUW', allyTeam: ['Neeko', 'Garen', 'Lux', 'Sona', 'Ashe'], enemyTeam: ['Brand', 'Ziggs', 'Jinx', 'Sett', 'Soraka'], earlyScore: 66, midScore: 71, lateScore: 69, deaths4: 3, killsAssists: 21, csm: 201, goldDiff15: 120, ...MOCK_BUILD },
  ],
  championPool: [
    { champion: 'Ivern', games: 3, wins: 3, losses: 0, wr: 100, kda: '6.3', cs: '5.0' },
    { champion: 'Neeko', games: 3, wins: 2, losses: 1, wr: 66.7, kda: '4.1', cs: '5.4' },
    { champion: 'Hwei',  games: 1, wins: 0, losses: 1, wr: 0, kda: '1.0', cs: '9.0' },
    { champion: 'Ahri',  games: 1, wins: 0, losses: 1, wr: 0, kda: '2.0', cs: '6.7' },
  ],
  collections: { played: 86, total: 171 },
  lens: { score: 60, series: [36, 44, 76, 76, 60, 36], avgDeaths: 4.7 },
  championPerformance: [
    { champion: 'Ivern', record: '50W-40L', kda: '2.4/3.6/11.9', cs: '5/15' },
    { champion: 'Neeko', record: '97W-69L', kda: '5.4/4.5/9.4',  cs: '5/15' },
    { champion: 'Hwei',  record: '39W-44L', kda: '5.1/5.3/8.7',  cs: '5/15' },
  ],
  featureCards: [
    { id: 'overlays',    label: 'Overlays',    icon: '⊞', desc: 'In-game overlays' },
    { id: 'collections', label: 'Collections', icon: '◈', desc: 'Skins owned · 50/1837' },
  ],
};

const MOCK_ROLES = ['Top', 'Jungle', 'Mid', 'ADC', 'Support'];
const MOCK_CHAMP_POOLS = [
  ['Jinx', 'Caitlyn', 'Jhin', 'Kaisa'],
  ['Thresh', 'Nautilus', 'Blitzcrank', 'Leona'],
  ['Zed', 'Yasuo', 'Akali', 'Ahri'],
  ['LeeSin', 'Vi', 'Elise', 'Graves'],
  ['Darius', 'Fiora', 'Camille', 'Renekton'],
];

export const MOCK_TOP_LEAGUE = Array.from({ length: 20 }).map((_, i) => ({
  rank: i + 1,
  summonerName: `Player${i + 1}#EUW`,
  role: MOCK_ROLES[i % MOCK_ROLES.length],
  topChampions: MOCK_CHAMP_POOLS[i % MOCK_CHAMP_POOLS.length],
  lp: 1200 - i * 14,
  wins: 300 - i * 3,
  losses: 250 - i,
  kda: (2.1 + (i % 7) * 0.4).toFixed(1),
}));

function mockLivePlayer(teamId, gameName, tagLine, champion, rank, lp, spells, extra = {}) {
  return {
    puuid: `${gameName}-mock`,
    teamId,
    champion,
    championName: extra.championName || champion,
    profileIconId: 29,
    spell1Id: spells[0],
    spell2Id: spells[1],
    keystone: extra.runes?.[0] || 8229,
    primaryStyle: extra.runes?.[1] || 8200,
    subStyle: extra.runes?.[2] || 8100,
    gameName,
    tagLine,
    riotId: `${gameName}#${tagLine}`,
    rank,
    lp,
    wins: extra.wins ?? 15,
    losses: extra.losses ?? 10,
    isSelf: !!extra.isSelf,
    role: extra.role || 'Mid',
    champGames: extra.champGames ?? 11,
    champWins: extra.champWins ?? Math.round((extra.champWr ?? 72.7) * (extra.champGames ?? 11) / 100),
    champWr: extra.champWr ?? 72.7,
    streak: extra.streak ?? 3,
    last3: extra.last3 ?? (extra.streak < 0 ? [false, false, true] : [true, true, false]),
    dodge: extra.dodge ?? (extra.streak <= -3),
  };
}

export const MOCK_LIVE_GAME = {
  gameId: 1,
  queueId: 420,
  queueName: 'Solo/Duo',
  gameLength: 612,
  bans: [
    { teamId: 100, champion: 'Yasuo' },
    { teamId: 100, champion: 'Zed' },
    { teamId: 100, champion: 'Kayn' },
    { teamId: 100, champion: 'KaiSa' },
    { teamId: 100, champion: 'Leblanc' },
    { teamId: 200, champion: 'Ahri' },
    { teamId: 200, champion: 'Thresh' },
    { teamId: 200, champion: 'Jinx' },
    { teamId: 200, champion: 'LeeSin' },
    { teamId: 200, champion: 'Aatrox' },
  ],
  blue: [
    mockLivePlayer(100, 'five fingers', 'EUW', 'Neeko', 'Master', 335, [4, 14], { isSelf: true, role: 'Mid', champGames: 14, champWr: 64.3, streak: 4, wins: 18, losses: 12 }),
    mockLivePlayer(100, 'BlueJungle', 'EUW', 'Ivern', 'Diamond I', 78, [4, 11], { role: 'Jungle', champGames: 8, champWr: 62.5, streak: 2 }),
    mockLivePlayer(100, 'BlueMid', 'EUW', 'Orianna', 'Master', 210, [4, 12], { role: 'Mid', champGames: 20, champWr: 55.0, streak: -3, last3: [false, false, false], dodge: true }),
    mockLivePlayer(100, 'BlueAdc', 'EUW', 'Jinx', 'Grandmaster', 412, [4, 7], { role: 'ADC', champGames: 11, champWr: 72.7, streak: 5 }),
    mockLivePlayer(100, 'BlueSup', 'EUW', 'Thresh', 'Diamond II', 44, [4, 14], { role: 'Support', champGames: 9, champWr: 44.4, streak: 1 }),
  ],
  red: [
    mockLivePlayer(200, 'RedTop', 'EUW', 'Renekton', 'Master', 188, [4, 12], { role: 'Top', champGames: 7, champWr: 57.1, streak: 3 }),
    mockLivePlayer(200, 'RedJungle', 'EUW', 'Viego', 'Master', 240, [4, 11], { role: 'Jungle', champGames: 16, champWr: 68.8, streak: 6 }),
    mockLivePlayer(200, 'RedMid', 'EUW', 'Viktor', 'Challenger', 902, [4, 12], { role: 'Mid', champGames: 12, champWr: 58.3, streak: -1 }),
    mockLivePlayer(200, 'RedAdc', 'EUW', 'Caitlyn', 'Grandmaster', 501, [4, 7], { role: 'ADC', champGames: 10, champWr: 50.0, streak: 2 }),
    mockLivePlayer(200, 'RedSup', 'EUW', 'Lulu', 'Diamond I', 92, [4, 3], { role: 'Support', champGames: 6, champWr: 83.3, streak: 4 }),
  ],
};